### PR TITLE
Addition of difference with Selenium update fix #740

### LINKED ISSUE #740: [Selenium 3.0] Update from Selenium 2 to Selenium 3
## Description
selenium update.

## Additional functions
- Update Selenium version to `3.0.1`
- Add webdrivermanager version `1.6.2`
- Update travisCI Firefox version to `52.9.0esr`
- Added property of geckodriver and webdrivermanager
- Implement setup on `FirefoxDriverFactoryBean.java` to use geckodriver
- Add test method to Readme

## Possible Solutions
Resolving errors with selenium update.
- Implement `WaitWebDriverEventListener.java` due to bug of geckodriver  
- To avoid Firefox crash, put `driver.get("about:config")` before `driver.quit()`  
- Create `WebDriverOperations#getTextMatchLink` for getting webElement containing blank literal
- Fix `ElTest#test05_URL_Link` for link access impossible at Jenkins

## Affects Version/s
* 5.X.X.RELEASE

## Fix Version/s
- [x] 5.5.1
- [x] 5.4.2 (Apply changes without selenium 3 unique.)

## Issue Links
* #XXX

### PR DESCRIPTION
**Pull request by btiwahorisu**
Please review #740 
Based on the following PR, I incorporated the correction not related to the Selenium update.
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/pull/744

### CODE REVIEW

File: terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/FunctionTestSupport.java [hunk 1]
```diff
@@ -182,6 +182,7 @@ private WebDriver newWebDriver() {
     protected void quitDefaultWebDriver() {
         if (driver != null) {
             try {
+                driver.get("about:config");
```
Comment (yoshikawaa) [inline terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/FunctionTestSupport.java]: - [ ] Why need this? Please re-consider based #768.

File: terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/el/ElTest.java [hunk 2]
```diff
@@ -270,9 +270,8 @@ public void test05_URL_Link() {
...
                         "http://localhost:8080/terasoluna-gfw-functionaltest-web/el/output_05_04?name=tera%261"));
         // inheriting of query Test
-        driver.findElement(By.id("linkUOutput")).findElement(By.linkText(
-                "http://localhost:8080/terasoluna-gfw-functionaltest-web/el/output_05_04?name=tera%261"))
-                .click();
+        driver.navigate().to(applicationContextUrl
+                + "/el/output_05_04?name=tera%261");
     }
 
     @Test(expected = NoSuchElementException.class)
```
Comment (yoshikawaa) [inline terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/el/ElTest.java]: https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/pull/744/files#diff-79f1423a88c365fcc49e2cd3e4f177c0R40 and etc...
- [ ] Please re-consider based #774 #773.

Comment (btiwahorisu) [reply terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/el/ElTest.java]: The correction not related to selenium update was taken in reference to #774 #773.
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/pull/806/commits/fd5884433068e7bc6a3870542ec56cf60fd56f56
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/pull/806/commits/7676ad1d32b061b1f69669705ab8bca083469f55

File: terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/FunctionTestSupport.java (hunk 1 above)
Comment (btiwahorisu) [reply terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/FunctionTestSupport.java]: Confirmation of ABC has leaked.
I deleted in the same way because it has been deleted in ABC.
54bd477db78b89598512792318284aaed9458bc5

File: terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java [hunk 3]
```diff
@@ -87,17 +87,19 @@ public void test02_01_useCaseControllerHandling() {
...
         assertThat(dbLogProvider.countContainsMessageAndLevelsAndLogger(
                 "\\[e.xx.9999\\] 2_1 Continue", "INFO",
                 "org.terasoluna.gfw.common.exception.ExceptionLogger.Monitoring"),
-                is(1L));
+                is(retryTimes));
 
         assertThat(dbLogProvider.countContainsByRegexExceptionMessage(null,
-                null, "2_1 Continue*", "..*ContinueException..*"), is(1L));
+                null, "2_1 Continue*", "..*ContinueException..*"), is(
+                        retryTimes));
```
Comment (yoshikawaa) [inline terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java]: - [ ] Unnecessary changes. (HtmlUnit unique.)

File: terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/ChromeDriverFactoryBean.java [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+    public Class<?> getObjectType() {
+        return ChromeDriver.class;
+    }
+
+    @Override
+    public boolean isSingleton() {
+        return false;
+    }
+
+}
```
Comment (yoshikawaa) [inline terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/ChromeDriverFactoryBean.java]: - [ ] Unnecessary changes. (Unnecessary factory bean.)

File: terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/InternetExplorerDriverFactoryBean.java [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+    public Class<?> getObjectType() {
+        return InternetExplorerDriver.class;
+    }
+
+    @Override
+    public boolean isSingleton() {
+        return false;
+    }
+
+}
```
Comment (yoshikawaa) [inline terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/InternetExplorerDriverFactoryBean.java]: - [ ] Unnecessary changes. (Unnecessary factory bean.)

File: terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/FirefoxDriverFactoryBean.java [hunk 6]
```diff
@@ -13,7 +13,7 @@
  * either express or implied. See the License for the specific language
  * governing permissions and limitations under the License.
  */
-package org.terasoluna.gfw.functionaltest.app;
+package org.terasoluna.gfw.functionaltest.app.webdrivers;
```
Comment (yoshikawaa) [inline terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/FirefoxDriverFactoryBean.java]: - [ ] Unnecessary changes. (5.4.x needs only firefox factory bean.)

File: terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/ChromeDriverFactoryBean.java (hunk 4 above)
Comment (btiwahorisu) [reply terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/ChromeDriverFactoryBean.java]: returned a fix for the added factory bean.
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/pull/806/commits/af8a63b38e21e4f50b51fe8110901876c485f5b4

File: terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/InternetExplorerDriverFactoryBean.java (hunk 5 above)
Comment (btiwahorisu) [reply terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/InternetExplorerDriverFactoryBean.java]: fixed by the next commit.
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/pull/806/commits/af8a63b38e21e4f50b51fe8110901876c485f5b4

File: terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/FirefoxDriverFactoryBean.java (hunk 6 above)
Comment (btiwahorisu) [reply terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/FirefoxDriverFactoryBean.java]: fixed by the next commit.
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/pull/806/commits/af8a63b38e21e4f50b51fe8110901876c485f5b4

File: terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java (hunk 3 above)
Comment (btiwahorisu) [reply terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java]: the fix has been restored.
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/pull/806/commits/195d8eb7a5d5506d2699add55dd77be1804b02c1
